version: '3.1'

services:
  sql: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      MSSQL_SA_PASSWORD: Your_password123!
      ACCEPT_EULA: "Y"    
    
  games-service:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DatascopeTest=Server=sql;database=DataScopeTest;user id=sa;password=Your_password123!;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockertest.pfx
    depends_on:
      - sql
    image: datascopetest    
    volumes:
      - C:\Users\daveo\.aspnet\https:/https/
    entrypoint: sh -c "sleep 5 && dotnet DatascopeTest.dll"  
    
  postman:
    image: postman/newman_alpine33
    command: run Games.postman_collection.json
     -e Local.postman_environment.json
     --delay-request 12000
     --insecure
    depends_on:
      - sql
      - games-service
    volumes:
      - ./postman-collections:/etc/newman
    
    