version: '3.1'

services:
  sql: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      MSSQL_SA_PASSWORD: Your_password123!
      ACCEPT_EULA: "Y"    

  integration:
    build: . 
    depends_on:
      - sql
    image: datascopetest-integrationtests:latest
    environment:
      - ConnectionStrings__DatascopeTestIntegrationTests=Server=sql;database=DataScopeTest.IntegrationTests;user id=sa;password=Your_password123!;TrustServerCertificate=True
    command: ["./wait-for-it.sh", "db", "-t", "120", "--", "dotnet", "test"]
    