version: '3.1'

services:
  sql: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      MSSQL_SA_PASSWORD: ${saPassword}
      ACCEPT_EULA: "Y"    

  integration: 
    depends_on:
      - sql
    image: datascopetest-integrationtests:latest
    environment:
      - ConnectionStrings__DatascopeTestIntegrationTests=Server=sql;database=DataScopeTest.IntegrationTests;user id=sa;password=${saPassword};TrustServerCertificate=True
    