version: '3.1'

services:
  sql: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      MSSQL_SA_PASSWORD: Your_password123!
      # SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    
  games-service:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ConnectionStrings__DatascopeTest=${ConnectionStrings__DatascopeTestIntegrationTests}      
      - ConnectionStrings__DatascopeTest=Server=sql;database=DataScopeTest;user id=sa;password=Your_password123!;TrustServerCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockertest.pfx
      # - ASPNETCORE_HTTPS_PORT=44311
    depends_on:
      - sql
    image: datascopetest    
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/    
    ports:
      - "5126:443"
    
  postman:
    image: postman/newman_alpine33
    command: run Games.postman_collection.json
     -e Local.postman_environment.json
     --delay-request 10000
     --insecure
    depends_on:
      - sql
      - games-service
    volumes:
      - ./postman-collections:/etc/newman
    
    