version: '3.1'

services:
  postman:
    image: postman/newman_alpine33
    command: run Games.postman_collection.json
     -e Local.postman_environment.json
     --insecure
    depends_on:
      - sql
      - games-service
    volumes:
      - ./postman-collections:/etc/newman

  sql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  games-service:
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ConnectionStrings__DatascopeTest=${ConnectionStrings__DatascopeTestIntegrationTests}
      # - ConnectionStrings__DatascopeTest=Server=sql;database=DataScopeTest.IntegrationTests;user id=sa;password=Your_password123
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=\https\aspnetapp.pfc    
    depends_on:
      - sql
    image: datascopetest    
    volumes:
      - ${USERPROFILE}\.aspnet\https:\https\
    build: .
    