pipeline {
  agent any

  triggers {
    pollSCM('* * * * *')
  }

  stages {
    // stage ('Clean workspace') {
    //   steps {
    //     cleanWs()
    //   }
    // } 

    stage('Restore packages') {
      steps {
        bat "dotnet restore Api/DatascopeTest.sln"
      }
    }

    stage('Build') {
      steps {
        bat "dotnet build Api/DatascopeTest.sln"
      }
    }

    stage('Unit Tests') {
      steps {
        bat "dotnet test API/DatascopeTest.Tests/DatascopeTest.Tests.csproj"
      }
    }

    stage('Print ConStr') {
      steps {        
        echo "connection string ${env.ConnectionStrings__DatascopeTestIntegrationTests}"
      }
    }

    stage('Integration Test') {
      steps {
        bat "dotnet test API/DatascopeTests.IntegrationTests/DatascopeTests.IntegrationTests.csproj"
      }
    }
  }
}