pipeline {
  agent any

  triggers {
    pollSCM('* * * * *')
  }

  stages {
    // stage ('Clean workspace') {
    //   steps {
    //     cleanWs()
    //   }
    // } 

    stage('Build') {
      steps {
        bat "dotnet restore Api/DatascopeTest.sln"
        bat "dotnet build Api/DatascopeTest.sln"
      }
    }

    stage('Unit Tests') {
      steps {
        bat "dotnet test API/DatascopeTest.Tests/DatascopeTest.Tests.csproj"
      }
    }    

    stage('Integration Test') {
      steps {        
        dir('Api') {
          bat "docker build -f test.Dockerfile -t datascopetest-integrationtests ."
        }        
        bat "docker-compose -f items/api/docker-compose.yml up --abort-on-container-exit"
        bat "docker-compose -f items/api/docker-compose.yml down"
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('Api') {          
          bat "docker build -f api.Dockerfile -t datascopetest ."
        }    
      }
    }

    stage('Run EE Tests') {
      steps {
        bat "docker-compose -f items/api/docker-compose.postman.yml up --abort-on-container-exit"
        bat "docker-compose -f items/api/docker-compose.postman.yml down"
      }
    }
  }
}