name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./DatascopeTest.sln
    - name: Build API
      run: dotnet build API/DatascopeTest/DatascopeTest.csproj --no-restore
    - name: Build Tests
      run: dotnet build API/DatascopeTest.Tests/DatascopeTest.Tests.csproj --no-restore
    - name: Test
      run: dotnet test API/DatascopeTest.Tests/DatascopeTest.Tests.csproj --no-build --verbosity normal
